// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouAndIdol.Contexts;

#nullable disable

namespace YouAndIdol.Migrations
{
    [DbContext(typeof(YouAndIdolContext))]
    [Migration("20260921031535_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("YouAndIdol.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("YouAndIdol.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bugdet")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("YouAndIdol.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Item");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("YouAndIdol.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("YouAndIdol.Models.Expense", b =>
                {
                    b.HasBaseType("YouAndIdol.Models.Item");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PaymentrMethodId_Expense");

                    b.HasIndex("PaymentMethodId");

                    b.HasDiscriminator().HasValue("Expense");
                });

            modelBuilder.Entity("YouAndIdol.Models.Income", b =>
                {
                    b.HasBaseType("YouAndIdol.Models.Item");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccountId");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PaymentMethodId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_EXCLUSIVE", "(([PaymentMethodId] IS NOT NULL) + ([AccountId] IS NOT NULL) = 1) OR (([PaymentMethodId] IS NOT NULL) + ([AccountId] IS NOT NULL) = 0)");
                        });

                    b.HasDiscriminator().HasValue("Income");
                });

            modelBuilder.Entity("YouAndIdol.Models.Transfer", b =>
                {
                    b.HasBaseType("YouAndIdol.Models.Item");

                    b.Property<int?>("FromAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromPaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToPaymentMethodId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("FromPaymentMethodId");

                    b.HasIndex("ToAccountId");

                    b.HasIndex("ToPaymentMethodId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_TRANSFER", "((([FromPaymentMethodId] IS NOT NULL) + ([FromAccountId] IS NOT NULL) = 1) AND (([ToPaymentMethodId] IS NOT NULL) + ([ToAccountId] IS NOT NULL) = 1)) OR (([FromPaymentMethodId] IS NOT NULL) + ([FromAccountId] IS NOT NULL) + ([ToPaymentMethodId] IS NOT NULL) + ([ToAccountId] IS NOT NULL) = 0)");
                        });

                    b.HasDiscriminator().HasValue("Transfer");
                });

            modelBuilder.Entity("YouAndIdol.Models.Category", b =>
                {
                    b.HasOne("YouAndIdol.Models.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("YouAndIdol.Models.Item", b =>
                {
                    b.HasOne("YouAndIdol.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YouAndIdol.Models.Expense", b =>
                {
                    b.HasOne("YouAndIdol.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Expenses")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("YouAndIdol.Models.Income", b =>
                {
                    b.HasOne("YouAndIdol.Models.Account", "Account")
                        .WithMany("Incomes")
                        .HasForeignKey("AccountId");

                    b.HasOne("YouAndIdol.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Incomes")
                        .HasForeignKey("PaymentMethodId");

                    b.Navigation("Account");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("YouAndIdol.Models.Transfer", b =>
                {
                    b.HasOne("YouAndIdol.Models.Account", "FromAccount")
                        .WithMany("TransferFroms")
                        .HasForeignKey("FromAccountId");

                    b.HasOne("YouAndIdol.Models.PaymentMethod", "FromPaymentMethod")
                        .WithMany("TransferFroms")
                        .HasForeignKey("FromPaymentMethodId");

                    b.HasOne("YouAndIdol.Models.Account", "ToAccount")
                        .WithMany("TransferTos")
                        .HasForeignKey("ToAccountId");

                    b.HasOne("YouAndIdol.Models.PaymentMethod", "ToPaymentMethod")
                        .WithMany("TransferTos")
                        .HasForeignKey("ToPaymentMethodId");

                    b.Navigation("FromAccount");

                    b.Navigation("FromPaymentMethod");

                    b.Navigation("ToAccount");

                    b.Navigation("ToPaymentMethod");
                });

            modelBuilder.Entity("YouAndIdol.Models.Account", b =>
                {
                    b.Navigation("Incomes");

                    b.Navigation("TransferFroms");

                    b.Navigation("TransferTos");
                });

            modelBuilder.Entity("YouAndIdol.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("YouAndIdol.Models.PaymentMethod", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");

                    b.Navigation("TransferFroms");

                    b.Navigation("TransferTos");
                });
#pragma warning restore 612, 618
        }
    }
}
